version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "playwright-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t5ib1whzto5d"
s3_prefix = "playwright-serverless"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["RenderScreenshot=002433976330.dkr.ecr.us-west-2.amazonaws.com/playwright-serverless"]
