AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  playwright-serverless

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  Playwright:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 1600
      Timeout: 100
      Description: Lambda function with headless playwright run time env
      Events:
        ReadabilityBotNewURL:
          Type: SQS
          Properties:
            Queue: !Ref ReadabilityBotURLQueue
            BatchSize: 10

    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./render-html
      Dockerfile: Dockerfile

  ReadabilityStaticHostStore:
    Type: AWS::S3::Bucket
    Properties:

  TwitterBotsEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TwitterBotEvent
      Tags:
        - Key: readability # name of related bot
          Value: newUrlTopic

  ReadabilityURLQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !GetAtt TwitterBotsEventsTopic.Arn
      Endpoint: !GetAtt ReadabilityBotURLQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true
      FilterPolicy: '{"event": ["new-readability-url"]}'

  ReadabilityBotURLQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30
      DelaySeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
      Tags:
        - Key: readability # name of related bot
          Value: URLQueue

  DeadLetterQueue:
    Type: AWS::SQS::Queue


Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  TwitterBotsEvents:
    Description: "Arn for Twitter bots events SNS"
    Value: !Ref TwitterBotsEventsTopic

  PlaywrightFunctionIamRole:
    Description: "Implicit IAM Role created for Render Screenshot function"
    Value: !GetAtt playwrightRole.Arn
