AWSTemplateFormatVersion: 2010-09-09
Description: >-
  playwright-serverless

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  RenderScreenshot:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 100
      Description: Render and screenshot the attached HTML string
      Events:
        RenderScreenshot:
          Type: Api
          Properties:
            Path: /render_screenshot
            Method: post
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./render-screenshot
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RenderScreenshotApi:
    Description: "API Gateway endpoint URL for Prod stage for RenderScreenshot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/render_screenshot/"
  RenderScreenshotFunction:
    Description: "Render Screenshot Lambda Function ARN"
    Value: !GetAtt RenderScreenshotFunction.Arn
  RenderScreenshotFunctionIamRole:
    Description: "Implicit IAM Role created for Render Screenshot function"
    Value: !GetAtt RenderScreenshotFunctionRole.Arn
